/* automatically generated by rust-bindgen */

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals
)]
#![cfg(target_os = "macos")]

#[macro_use]
extern crate objc;
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
#[repr(transparent)]
pub struct struct_Foo(pub id);
impl std::ops::Deref for struct_Foo {
    type Target = id;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
unsafe impl objc::Message for struct_Foo {}
impl struct_Foo {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(objc::class!(Foo), alloc) })
    }
}
impl<ObjectType: 'static> interface_Foo<ObjectType> for struct_Foo {}
pub trait interface_Foo<ObjectType>:
    Sized + std::ops::Deref + objc::Message
{
    unsafe fn get(self) -> u64
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(self, get)
    }
}
#[repr(transparent)]
pub struct struct_FooMultiGeneric(pub id);
impl std::ops::Deref for struct_FooMultiGeneric {
    type Target = id;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
unsafe impl objc::Message for struct_FooMultiGeneric {}
impl struct_FooMultiGeneric {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(objc::class!(FooMultiGeneric), alloc) })
    }
}
impl<KeyType: 'static, ObjectType: 'static>
    interface_FooMultiGeneric<KeyType, ObjectType> for struct_FooMultiGeneric
{
}
pub trait interface_FooMultiGeneric<KeyType, ObjectType>:
    Sized + std::ops::Deref + objc::Message
{
    unsafe fn objectForKey_(self, key: u64) -> u64
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(self, objectForKey: key)
    }
}
