/* automatically generated by rust-bindgen */

#![allow(
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals
)]
#![cfg(target_os = "macos")]

#[macro_use]
extern crate objc;
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
pub struct struct_Foo(id);
impl std::ops::Deref for struct_Foo {
    type Target = id;
    fn deref(&self) -> &Self::Target {
        unsafe { ::core::mem::transmute(self.0) }
    }
}
unsafe impl objc::Message for struct_Foo {}
impl interface_Foo for struct_Foo {}
pub trait interface_Foo: Sized + std::ops::Deref + objc::Message {
    unsafe fn func(
        self,
    ) -> ::std::option::Option<
        unsafe extern "C" fn(
            arg1: ::std::os::raw::c_char,
            arg2: ::std::os::raw::c_short,
            arg3: f32,
        ) -> ::std::os::raw::c_int,
    >
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(self, func)
    }
    unsafe fn setFunc_(
        self,
        func: ::std::option::Option<
            unsafe extern "C" fn() -> ::std::os::raw::c_int,
        >,
    ) where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(self, setFunc: func)
    }
}
